#PBS -N 13
#PBS -l nodes=1:ppn=24
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/autism/data/aloft/temp/
#PBS -e /gpfs/home/guosa/hpc/autism/data/aloft/temp/
cd /gpfs/home/guosa/hpc/autism/data/aloft
mkdir ./temp/chr13
bcftools view -e 'ALT ="-" | REF ="-"' -t 13 All_samples_Exome_QC.clean.vcf.gz -Oz -o ./chr/All_samples_Exome_QC.clean.chr13.vcf.gz
java -Djava.io.tmpdir=./temp/chr13 -Xmx64g -jar beagle.16May19.351.jar gt=./chr/All_samples_Exome_QC.clean.chr13.vcf.gz ref=/gpfs/home/guosa/hpc/db/hg19/beagle/EUR/chr13.1kg.phase3.v5a.EUR.vcf.gz map=/gpfs/home/guosa/hpc/db/hg19/beagle/plink.chr13.GRCh37.map out=./chr/All_samples_Exome_QC.chr13.vcf
