#PBS -N 3
#PBS -l nodes=1:ppn=8
#PBS -M Guo.shicheng@marshfieldresearch.org
#PBS -m abe
#PBS -o /gpfs/home/guosa/hpc/autism/data/2lof/beagle/temp/temp/
#PBS -e /gpfs/home/guosa/hpc/autism/data/2lof/beagle/temp/temp/
cd /gpfs/home/guosa/hpc/autism/data/2lof/beagle/temp
convert2annovar.pl -format vcf4 -allsample -withfreq All_samples_Exome_QC.chr3.vcf.vcf.gz > ./annovar/All_samples_Exome_QC.chr3.avinput
table_annovar.pl ./annovar/All_samples_Exome_QC.chr3.avinput /gpfs/home/guosa/hpc/tools/annovar/humandb/ --thread 4 -buildver hg19 --csvout -out ./annovar/chr3 -remove -protocol refGene,dbnsfp35a,gwasCatalog,wgRna,targetScanS,tfbsConsSites -operation gx,f,r,r,r,r -nastring . -otherinfo -polish -xref /gpfs/home/guosa/hpc/tools/annovar/humandb/gene_fullxref.txt
